"""
Generate the supplementary tables of per-seed calibration estimates.

Reads image_level_bootstrap.json, written by analyse_image_level.py, and emits
two LaTeX fragments:

  S1   per-seed point estimates with 95% image-level bootstrap percentile
       intervals, one table per configuration
  S1b  width comparison between the prediction-level and image-level bootstrap,
       reported as a sensitivity check

Formatting only -- nothing is recomputed here.

Usage:
    python make_supplementary_tables.py
"""

import json
import numpy as np
from pathlib import Path
from paths import CALIB

OUT = CALIB
SRC = OUT / "image_level_bootstrap.json"

METRICS = [("D-ECE", "D-ECE"), ("Adaptive ECE", "Adaptive ECE"),
           ("Brier", "Brier"), ("NLL", "NLL")]

ORDER = ["A_independent", "C_shallow", "C_deep", "B_shared",
         "gapfc_A_independent", "gapfc_B_shared", "F_frozen"]


def fmt(v, digits=4):
    return f"{v:.{digits}f}" if v is not None else "---"


def cell(m, digits=4):
    """Point estimate with its interval, formatted as "est [lo, hi]"."""
    return (f"{m['point']:.{digits}f} "
            f"[{m['img_ci'][0]:.{digits}f}, {m['img_ci'][1]:.{digits}f}]")


if __name__ == "__main__":
    if not SRC.exists():
        raise SystemExit(f"not found: {SRC}，run this first: image_level_analysis.py")

    data = json.load(open(SRC))
    lines = []
    lines.append("% Generated by make_supplementary_tables.py -- do not edit by hand")
    lines.append("% Intervals are image-level bootstrap percentile intervals")
    lines.append("% Include with \\input{supplementary_tables}")
    lines.append("")

    # ---------- S1: one table per configuration ----------
    for cfg in ORDER:
        if cfg not in data:
            print(f"[skipped] {cfg} not present in the data")
            continue
        info = data[cfg]
        rows = info["rows"]
        if not rows:
            continue
        disp = info["display"]

        lines.append(r"\begin{table}[htbp]")
        lines.append(r"\centering")
        lines.append(f"\\caption{{Per-seed calibration estimates for {disp}, with "
                     f"95\\% image-level bootstrap percentile intervals "
                     f"($B = 1000$ resamples). $n$ is the number of predictions; "
                     f"all models were evaluated on the same 198 validation "
                     f"images.}}")
        lines.append(f"\\label{{tab:supp-{cfg.replace('_','-')}}}")
        lines.append(r"\resizebox{\textwidth}{!}{%")
        lines.append(r"\begin{tabular}{ccllll}")
        lines.append(r"\toprule")
        lines.append(r"Seed & $n$ & D-ECE & Adaptive ECE & Brier & NLL \\")
        lines.append(r"\midrule")
        for r in rows:
            cells = [str(r["seed"]), str(r["n_pred"])]
            for key, _ in METRICS:
                cells.append(cell(r[key]))
            lines.append(" & ".join(cells) + r" \\")
        lines.append(r"\bottomrule")
        lines.append(r"\end{tabular}%")
        lines.append(r"}")
        lines.append(r"\end{table}")
        lines.append("")

    # ---------- S1b: interval width, the two bootstrap schemes ----------
    lines.append(r"\begin{table}[htbp]")
    lines.append(r"\centering")
    lines.append(r"\caption{Width of prediction-level and image-level bootstrap "
                 r"percentile intervals for D-ECE, averaged over the seeds of each "
                 r"configuration. The ratio is the image-level width divided by "
                 r"the prediction-level width.}")
    lines.append(r"\label{tab:supp-bootstrap-comparison}")
    lines.append(r"\begin{tabular}{lccc}")
    lines.append(r"\toprule")
    lines.append(r"Configuration & Prediction-level width & Image-level width & Ratio \\")
    lines.append(r"\midrule")

    all_ratios = []
    for cfg in ORDER:
        if cfg not in data or not data[cfg]["rows"]:
            continue
        disp = data[cfg]["display"]
        pw, iw = [], []
        for r in data[cfg]["rows"]:
            m = r["D-ECE"]
            pw.append(m["pred_ci"][1] - m["pred_ci"][0])
            iw.append(m["img_ci"][1] - m["img_ci"][0])
        pw, iw = np.array(pw), np.array(iw)
        ratios = iw / pw
        all_ratios.extend(ratios.tolist())
        lines.append(f"{disp} & {pw.mean():.4f} & {iw.mean():.4f} & "
                     f"{ratios.mean():.2f} \\\\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append("")
    lines.append(f"\\vspace{{2pt}}")
    lines.append(f"{{\\footnotesize Across all trained models the mean ratio is "
                 f"${np.mean(all_ratios):.2f}$ (range "
                 f"${min(all_ratios):.2f}$--${max(all_ratios):.2f}$).}}")
    lines.append(r"\end{table}")
    lines.append("")

    out = OUT / "supplementary_tables.tex"
    # back up any previous version
    if out.exists():
        bak = OUT / "supplementary_tables_predlevel.tex.bak"
        bak.write_text(out.read_text())
        print(f"previous version backed up to {bak.name}")

    out.write_text("\n".join(lines))
    print(f"wrote {out}")
    print(f"  {len([c for c in ORDER if c in data])} configuration tables")
    print(f"  interval width ratio: mean {np.mean(all_ratios):.3f}, "
          f"range {min(all_ratios):.3f}–{max(all_ratios):.3f}")