"""
Generate the supplementary table listing every inferential test reported in the
paper, so that the multiplicity discussion can be audited directly.

The values below are transcribed from the outputs of stats_dece.py,
stats_brier.py, stats_nll_adaptive_ece.py, stats_trend.py and
analyse_temperature_scaling.py. They are held here as a single cross-checked
table rather than recomputed, so that the count reported in the manuscript
(m = 26) has one authoritative source.

Usage:
    python make_test_inventory.py
"""

import numpy as np
from paths import CALIB

# (experiment, comparison, metric, t, p, d_z, n)
# d_z is None for the one-sample trend tests, which are reported without it.
TESTS = [
    # E1: independent vs fully shared, four metrics
    ("E1", "Independent vs fully shared",      "D-ECE",         3.324,  0.0127,  1.175, 8),
    ("E1", "Independent vs fully shared",      "Adaptive ECE",  2.713,  0.0301,  0.959, 8),
    ("E1", "Independent vs fully shared",      "Brier",         2.864,  0.0242,  1.012, 8),
    ("E1", "Independent vs fully shared",      "NLL",           2.987,  0.0203,  1.056, 8),
    # E1: linear trend across depths (six seeds with all four depths)
    ("E1", "Linear trend across depths",       "D-ECE",         3.436,  0.0185,  None,  6),
    ("E1", "Linear trend across depths",       "Adaptive ECE",  2.978,  0.0309,  None,  6),
    ("E1", "Linear trend across depths",       "Brier",         3.327,  0.0209,  None,  6),
    ("E1", "Linear trend across depths",       "NLL",           3.357,  0.0202,  None,  6),
    # E2: interaction (primary test), four metrics
    ("E2", "Interaction (primary test)",       "D-ECE",         2.590,  0.0359,  0.916, 8),
    ("E2", "Interaction (primary test)",       "Adaptive ECE",  1.863,  0.1047,  0.659, 8),
    ("E2", "Interaction (primary test)",       "Brier",         2.496,  0.0412,  0.882, 8),
    ("E2", "Interaction (primary test)",       "NLL",           2.586,  0.0362,  0.914, 8),
    # E2: residual cost under the GAP+FC head, four metrics
    ("E2", "Residual cost under GAP+FC head",  "D-ECE",         3.387,  0.0116,  1.198, 8),
    ("E2", "Residual cost under GAP+FC head",  "Adaptive ECE",  2.246,  0.0596,  0.794, 8),
    ("E2", "Residual cost under GAP+FC head",  "Brier",         2.616,  0.0346,  0.925, 8),
    ("E2", "Residual cost under GAP+FC head",  "NLL",           3.167,  0.0158,  1.120, 8),
    # E3: frozen-backbone control vs fully shared, four metrics
    ("E3", "Frozen backbone vs fully shared",  "D-ECE",        -0.951,  0.3854, -0.388, 6),
    ("E3", "Frozen backbone vs fully shared",  "Adaptive ECE",  0.337,  0.7500,  0.137, 6),
    ("E3", "Frozen backbone vs fully shared",  "Brier",         1.156,  0.3000,  0.472, 6),
    ("E3", "Frozen backbone vs fully shared",  "NLL",           1.379,  0.2264,  0.563, 6),
    # E4: gap surviving temperature scaling, two metrics
    ("E4", "Gap after temperature scaling",    "D-ECE",         4.135,  0.0044,  1.462, 8),
    ("E4", "Gap after temperature scaling",    "Brier",         2.879,  0.0237,  1.018, 8),
    # E4: AUC, one per classification head
    ("E4", "AUC, default head",                "AUC",          -3.311,  0.0129, -1.171, 8),
    ("E4", "AUC, GAP+FC head",                 "AUC",          -2.300,  0.0550, -0.813, 8),
    # E5: additional datasets
    ("E5", "Independent vs shared, CVC-ClinicDB", "D-ECE",      5.136,  0.0359,  2.965, 3),
    ("E5", "Independent vs shared, ETIS",         "D-ECE",     12.966,  0.0059,  7.486, 3),
]

BONFERRONI = 0.05 / len(TESTS)


def escape(s):
    return s.replace("&", r"\&")


def main():
    assert len(TESTS) == 26, f"expected 26 tests, found {len(TESTS)}"

    ps = [t[4] for t in TESTS]
    n_nominal = sum(1 for p in ps if p < 0.05)
    n_bonf = sum(1 for p in ps if p < BONFERRONI)

    L = [
        "% Generated by make_test_inventory.py -- do not edit by hand",
        "",
        r"\begin{table}[htbp]",
        r"\centering",
        f"\\caption{{Complete inventory of the {len(TESTS)} inferential tests "
        f"reported in this work, corresponding to the multiplicity discussion in "
        f"Section~\\ref{{sec:stats}}. Effect sizes are Cohen's $d_z$; the trend "
        f"tests are one-sample tests on per-seed slopes and are reported without "
        f"$d_z$. The Bonferroni threshold across all {len(TESTS)} tests is "
        f"$\\alpha = 0.05/{len(TESTS)} = {BONFERRONI:.4f}$.}}",
        r"\label{tab:supp-test-inventory}",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{llllrrrc}",
        r"\toprule",
        r"\# & Exp. & Comparison & Metric & $t$ & $p$ & $d_z$ & $n$ \\",
        r"\midrule",
    ]

    prev = None
    for i, (exp, comp, met, t, p, d, n) in enumerate(TESTS, 1):
        if prev is not None and exp != prev:
            L.append(r"\midrule")
        prev = exp
        dstr = f"{d:.3f}" if d is not None else "---"
        pstr = f"\\textbf{{{p:.4f}}}" if p < 0.05 else f"{p:.4f}"
        L.append(f"{i} & {exp} & {escape(comp)} & {escape(met)} & "
                 f"{t:.3f} & {pstr} & {dstr} & {n} \\\\")

    L += [
        r"\bottomrule",
        r"\end{tabular}%",
        r"}",
        "",
        r"\vspace{2pt}",
        f"{{\\footnotesize Boldface marks $p < 0.05$ uncorrected. "
        f"{n_nominal} of {len(TESTS)} tests reach nominal significance; "
        f"{n_bonf} clear the Bonferroni threshold of {BONFERRONI:.4f}. "
        f"The smallest $p$-value reported is {min(ps):.4f}.}}",
        r"\end{table}",
        "",
    ]

    out = CALIB / "supplementary_test_inventory.tex"
    out.write_text("\n".join(L))

    print(f"Wrote {out}")
    print(f"  tests            : {len(TESTS)}")
    print(f"  nominal p < 0.05 : {n_nominal}")
    print(f"  clear Bonferroni : {n_bonf} (threshold {BONFERRONI:.4f})")
    print(f"  smallest p       : {min(ps):.4f}")


if __name__ == "__main__":
    main()
